### ISSUE TITLE
Scape $ on variable substitution to deploy app json to marathon

### ISSUE THREAD

**Issue by kkdevops** [gondor/depcon#13]
I'm trying to deploy one app to marathon and my json has some internal variable managed by marathon like: **$HOST**, **$PORT0** and **$PORT1**, but _depcon_ try to replace with instance variable when upload file and show some errors....I need a way to scape these variable...

My app.json:
```
{
  "id": "appname",
  "cpus": "0.1",
  "mem": "256",
  "instances": 1,
  "cmd": "./bin/spark-class org.apache.spark.deploy.mesos.MesosClusterDispatcher --master zk://localhost:2181/mesos --zk localhost:2181 --host $HOST --port $PORT0 --webui-port $PORT1 --name spark_marathon_framework_name",
  "env": {
    "SPARK_USER": "root",
    "HADOOP_HOME": "/usr/lib/hadoop"
  },
  "ports": [
    32000,
    0
  ],
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "registry/myimage:latest",
      "network": "HOST"
    },
    "volumes": [
      {
        "containerPath": "/etc/localtime",
        "hostPath": "/etc/localtime",
        "mode": "RO"
      },
      {
        "containerPath": "/etc/hadoop/conf",
        "hostPath": "spark_marathon_hadoop_conf_dir",
        "mode": "RO"
      },
      {
        "containerPath": "/usr/lib/hadoop",
        "hostPath": "/usr/lib/hadoop",
        "mode": "RO"
      }
    ]
  },
  "healthChecks": [
    {
      "path": "/",
      "portIndex": 1,
      "protocol": "HTTP",
      "gracePeriodSeconds": 5,
      "intervalSeconds": 60,
      "timeoutSeconds": 10,
      "maxConsecutiveFailures": 3
    }
  ], "_hack": null
}
```

**Comment by gondor** [comment]
Good find.  Since depcon uses ```${PARAM}``` format your correct.  We should treat ```$PARAM``` without the ```{}``` as a non-depcon param (leave as is).  Will look into addressing this in the next 24 hours.

**Comment by gondor** [comment]
Ok, should be fixed.  I updated the binaries now version 0.5.  Also the ^^ JSON above is malformed, found another bug in not reporting this.  The CPU and Mem are numeric and should have "0.1" in quotes.

Let me know if this fix works for you for issue closure

**Comment by kkdevops** [comment]
ok, all work fine...thks.
