### ISSUE TITLE
Failed Starting certifier : Error: image library/depcon_proj_certifier not found

### ISSUE THREAD

**Issue by benmathews** [gondor/depcon#16]
Tried using the compose functionality. The certifier container is a locally built container.

```
$ depcon --verbose compose up certifier
INFO[0000] Project [depcon_proj]: Starting project      
INFO[0000] [0/8] [certifier]: Starting                  
Pulling repository docker.io/library/depcon_proj_certifier
ERRO[0003] Failed to pull image depcon_proj_certifier:latest: Error: image library/depcon_proj_certifier not found 
ERRO[0003] Failed Starting certifier : Error: image library/depcon_proj_certifier not found 
ERRO[0003] Failed to start: certifier : Error: image library/depcon_proj_certifier not found 
2016-03-16 12:31:25 ERROR [depcon]: Error: image library/depcon_proj_certifier not found
```

**Comment by gondor** [comment]
Could you try adding the :latest (or whatever is a valid tag) to your image definition in your compose file?  Also are you using a compose version 1 format?  Version 2 you would have had to declare it.  V2 won't be available for another couple weeks (waiting on libcompose to add support).

**Comment by gondor** [comment]
@benmathews re-open when you have the info.   After looking further (if its not V2) I think your issue is how your using your compose file.  would like to see it if possible.
