### ISSUE TITLE
Exit with non-zero return code when marathon app creation fails

### ISSUE THREAD

**Issue by ericachelis** [gondor/depcon#17]
It would be nice if depcon exited with a non-zero return code when an application was not successfully deployed because a defined ${PARAM} could not be substituted.

See example below:
```
$ depcon app create marathon.json --ignore=false
2016-03-25 18:16:46 WARNING [depcon]: Cannot find a value for varible ${test} which was defined in marathon.json

$ echo $?
0
```

This would allow for more seamless failure detection when automating deployments with depcon.

**Comment by ericachelis** [comment]
Another scenario is when the deployment descriptor is not valid json.  The application terminates with no indication of error:

```
$ echo '{notValidJson' > marathon.json

$ depcon app create marathon.json --verbose=true --wait=true
2016-03-25 18:45:03 INFO [depcon.marathon]: Creating Application from file: marathon.json

$ echo $?
0
```

When expecting parameter substitution in the deployment descriptor it is a bit more challenging validate the descriptor prior to calling depcon.

**Comment by gondor** [comment]
Good idea.  Thanks!

**Comment by gondor** [comment]
Ok fix has been made.  Should get a exit code of 1 when a command fails.  Binaries have been posted

**Comment by ericachelis** [comment]
Release 7.0 is now correctly responding with error codes in the scenarios reported above as well as several other error situations.  Thank you!
