### ISSUE TITLE
Feature Request: Configurable wait timeout for marathon

### ISSUE THREAD

**Issue by ericachelis** [gondor/depcon#18]
The `--wait` option for a marathon deployments uses a hard-coded 90 second value. If the application is not healthy within 90 seconds depcon exits with an error.  Some of our services take more than the default of 90 seconds to start.   It would be nice if we could override this value if the application is known to take more than 90 seconds to start.

Another idea would be to look at the [gracePeriodSeconds](https://mesosphere.github.io/marathon/docs/health-checks.html#health-check-options) for any defined marathon health-check, and if present use this as the default wait time.

**Comment by gondor** [comment]
How ironic you logged this!  I actually started adding support today for this.  I hit a scenario in our system where a service was taking long to start.  I like your idea of adding the gracePeriodSeconds.  I'm going to  offer a --timeout flag (trumps all), if not set look for gracePeriod.. and finally fallback to default.

**Comment by ericachelis** [comment]
Awesome thank you!

**Comment by gondor** [comment]
Ok support has been added and new binaries available.  On any of the app create/update/scale, etc commands you have the option of passing a duration with the flag ```-t or --wait-timeout```  .  

**Example: 
**```
depcon app create myapp.yml -w -t 120s
```

**Rules:**
1.  If --wait-timeout is specified it is used over any other (default, health check timeout, etc)
2.  If --wait-timeout is missing then the application healthcheck is compared against the default and whatever is highest wins.

**Comment by ericachelis** [comment]
I installed the latest binary release and validated the following scenarios:
* No `--wait-timeout` option present and no gracePeriodSeconds option defined as a marathon health check, the default 90 second value will be used.
* At least one Marathon health check is defined with gracePeriodSeconds > 90, the largest grace period will be used.
* The `--wait-timeout` option is specified, it will be used.

Looks great, thank you!

**Comment by ericachelis** [comment]
Whoops, reopening. Looks like the new logic is used on application creation but not in application update scenarios.  Perhaps passing the Application object (instead of nil) to the determineTimeout method will resolve the issue:
https://github.com/gondor/depcon/blob/2529ba533228195a429b28c06e9999358c0e5b4c/marathon/application.go#L114
https://github.com/gondor/depcon/blob/2529ba533228195a429b28c06e9999358c0e5b4c/marathon/application.go#L117

**Comment by gondor** [comment]
Thanks for pointing this out.  I just made the suggested changes and posted a new binary.  I haven't had time to test so if you don't mind :)

Also, I'm now publishing releases via GitHub (vs. previous BinTray).  You can see the newest release I just published at: https://github.com/gondor/depcon/releases

**Comment by ericachelis** [comment]
Works like a charm.  Thanks for the super-fast turn-around!
