### ISSUE TITLE
possible error on depcon install

### ISSUE THREAD

**Issue by kbroughton** [gondor/depcon#22]
I'm on go v1.6 [which says](https://github.com/golang/go/wiki/PackageManagementTools) setting the 
GO15VENDOREXPERIMENT is no longer needed.

The final line of output for
 ```go get -v github.com/gondor/depcon```
is
```../../work/src/github.com/gondor/depcon/compose/compose_wrapper.go:108: cannot range over c.project.Configs (type *config.Configs)```

Could you confirm if this is an actual problem or update the docs to mention it?

I'm using brew installed go on a mac, updated today
```> go version
> go version go1.6 darwin/amd64```

**Comment by kbroughton** [comment]
After setting the env var, i still get the error.
```
> export GO15VENDOREXPERIMENT=1
> go get -v github.com/gondor/depcon
github.com/gondor/depcon/compose
# github.com/gondor/depcon/compose
../../work/src/github.com/gondor/depcon/compose/compose_wrapper.go:108: cannot range over c.project.Configs (type *config.Configs)
```

**Comment by gondor** [comment]
Try using Git to pull the depcon source.  I'm not sure how "robust" vendor support is with ```go get``` right now.  I've had problems with other projects.   Otherwise if you don't care about having source just grab the binary from the release page.

Currently we have Travis building on both Go 1.5 and 1.6 with no issues.

**Comment by kbroughton** [comment]
git pull
make 
failed
go install: no install location for directory /Users/kestenbroughton/work/pkg/darwin_amd64/github.com/depcon outside GOPATH

I have it working with the binary download now.  Thanks.
